### ISSUE TITLE
issue with path to arethusa resources

### ISSUE THREAD

**Issue by balmas** [perseids-publications/treebank-template#24]
I've been working through getting the deployment to work using aws3 and cloudfront.
I have run into a small issue with the path to the arethusa resources.

In ArethusaWrapper, the path is set to 

`${process.env.PUBLIC_URL}/arethusa/`

When deployed at the root of the website, this then results in the path to the arethusa resources getting an extra '/'

e.g.

`alpheios.trees.com/arethusa//dist/arethusa.packages.min.js`

which is not working with the AWS webserver

If I remove the trailing slash it works great for my environment, but when I tested it on the origin repo, the yarn dev server is failing to find the the d3 code. I'm a little lost because I can't seem to reproduce that problem in my own yarn dev environment (using the alpheios-project/alpheios-trees repo), although I can't see any other differences .

Any thoughts?  I know the arethusa code uses a relative path back to the d3 module so maybe that's a factor here, but I can't figure out why it would work in one environment and not another with the same code.

**Comment by zfletch** [comment]
I was able to replicate the issue and it looks like the only reason it's working now is that GitHub pages resolves the double slash in `/arethusa//dist/arethusa.packages.min.js`.

I'm not sure how it could be working in one environment but not in another, but when I change `${process.env.PUBLIC_URL}/arethusa/` to `${process.env.PUBLIC_URL}/arethusa` in `ArethusaWrapper` and I also change `../../vendor/d3-3.4.13/d3.min.js` to `/../../vendor/d3-3.4.13/d3.min.js` in `public/arethusa/dist/arethusa.dep_tree.min.js`, everything seems to work.

If it turns out that it works in both environments, then we should probably make that change in [Arethusa](https://github.com/alpheios-project/arethusa/blob/gardener_widget/app/js/arethusa.dep_tree/services/dep_tree.js#L34) and the corresponding change in the Treebank Template.

**Comment by balmas** [comment]
agreed. I'll send a PR for the Arethusa change once I've confirmed it works with the AWS deployment.

**Comment by zfletch** [comment]
Fixed in https://github.com/perseids-publications/treebank-template/pull/26
