### ISSUE TITLE
getting started doc: add DOI instructions

### ISSUE THREAD

**Issue by balmas** [perseids-publications/treebank-template#40]
requested by nevenjovanovic

**Comment by zfletch** [comment]
This is a great idea. One thing I want to point out is that the instructions in the README are complicated because I wanted to include the DOI of the current release in the code of the release itself and that's not currently supported by the Zenodo GitHub integration. I emailed Zenodo support about this workflow and got this response:

> Unfortunately, there is no change on that front. We have no way to pre-reserve the DOI unless you do it manually (meaning, not automatic integration with GitHub). We understand the use case and we will have it in mind for future improvements and we believe we should provide something for this.
