### ISSUE TITLE
Alpheios integration: words annotated, but disambiguation data sometimes does not show up

### ISSUE THREAD

**Issue by nevenjovanovic** [perseids-publications/treebank-template#42]
Using the treebanks https://nevenjovanovic.github.io/treebank-template/fragment-SBJ-10-1-10/11 and https://nevenjovanovic.github.io/treebank-template/fragment-SBJ-10-1-10/12 (the same sentence, without the treebank diagram and with a partial one), at our site integrated with Alpheios and treebanks http://croala.ffzg.unizg.hr/eklogai/theca/10-sent-sbj/ the words 3, 5, 9-13, 20, 24, 26-28, 30 do not show disambiguation data, even those words which have multiple possible morphological identification.
Don't understand why is this happening, because the morphological data and lemmata are present in the source, for example:
```xml
<word id="24" form="ἀήθεις" lemma="ἀήθης" postag="a-p---ma-" relation="" head=""/>
<word id="25" form="," lemma="punc1" postag="u--------" relation="AuxX" head="0"/>
<word id="26" form="τροφῆς" lemma="τροφή" postag="n-s---fg-" relation="" head=""/>
<word id="27" form="δ’" lemma="δέ" postag="d-------p" relation="" head=""/>
<word id="28" form="ἡμέρου" lemma="ἥμερος" postag="a-s---fgp" relation="" head=""/>
<word id="29" form="παντελῶς" lemma="παντελῶς" postag="d-------p" relation="" head=""/>
<word id="30" form="ἀνεννοήτους" lemma="ἀνεννόητος" postag="a-p---ma-" relation="" head=""/>
<word id="31" form="." lemma="punc1" postag="u--------" relation="AuxK" head="0"/>
```
On the other hand, at another page of the same site: http://croala.ffzg.unizg.hr/eklogai/theca/ps-xen-athen-2-14-2/ all words are disambiguated according to source https://nevenjovanovic.github.io/treebank-template/ps-xen-2-14-2-16/1
I use mkdocs to produce the pages, but the sentences aligned with treebanks are HTML fragments.
Tested in Firefox and Chrome.

**Comment by balmas** [comment]
investigating...

**Comment by balmas** [comment]
This is caused by an inconsistency in how we handle encoding in Alpheios and Arethusa.  Alpheios sends a normalized to NFC version of the word text to Arethusa to find in the sentence, but Arethusa does not on its end apply the same normalization to the text in the treebank and thus it's not finding a match. I had taken this into account on the Alpheios end when data is received from Arethusa, but not in Arethusa when data is received from Alpheios.

So, this is a fix I need to make in Arethusa and I'll transfer the issue there.

In the meantime @nevenjovanovic there are two ways to workaround it:

1) you could normalize the treebank data files using the same algorithm as we do in Alpheios  (we use the javascript String.normalize('NFC') function

2) for words that aren't being found, you could specify the word_id specifically in the html attributes, as in the following example from the instructions:

```
Alpheios and Arethusa will use the context to try to find the word within the treebank data for a sentence that corresponds to the word in the text on the page. In most cases this will work well, but in certain circumstances, you may need to override the default behavior and specify which tokens in the treebank data correspond to the word on the page. The data-alpheios_tb_word attribute can be used to do this.


        <p data-alpheios_tb_sent="1">περὶ πολλοῦ ἂν ποιησαίμην, ὦ <span data-alpheios_tb_word="7">ἄνδρες</span>, τὸ τοιούτους ὑμᾶς ἐμοὶ δικαστὰς περὶ τούτου τοῦ πράγματος γενέσθαι,
          οἷοίπερ ἂν ὑμῖν αὐτοῖς εἴητε τοιαῦτα πεπονθότες·</p>
```
