### ISSUE TITLE
Add support for parameter to preselect a word

### ISSUE THREAD

**Issue by balmas** [perseids-publications/treebank-template#6]
In https://github.com/perseids-publications/treebank-template/blob/88fe935f6f43624430814a1c010d31d7adb952e6/src/components/ArethusaWrapper/ArethusaWrapper.js#L36

If you add support for passing the preselector parameter here (in the tbpub.json, the parameter name is defined as w:

```
    "TreebankRetriever": {
        "resource": "Gardener",
        "docIdentifier": "treebank",
        "preselector": "w"
      }
```

Arethusa would highlight the preselected word

**Comment by zfletch** [comment]
I tried it out in a new [branch](https://github.com/perseids-publications/treebank-template/tree/allow-other-arguments-to-arethusa) and it for the most part is works!

<img width="1232" alt="screenshot" src="https://user-images.githubusercontent.com/3039310/68508973-d8190380-023d-11ea-8f01-0d44ed9a0727.png">

What I'd like to figure out before merging is what the behavior of the `Next` and `Back` buttons should be. It seems like the word being selected disappears when [arethusaGoto](https://github.com/perseids-publications/treebank-template/blob/e4c6a8881c44a44d9a8118f9288ddbe920b10edb/src/components/ArethusaWrapper/ArethusaWrapper.js#L26) is called. This means that the next and back buttons may have to be real links (to reload Arethusa entirely) when there are query params.

**Comment by balmas** [comment]
hmm. that's an interesting question. I think it should probably not change the behavior of next/back. that is, I don't think carrying a preselected word forward when navigating across sentences makes sense. what do you think?

**Comment by zfletch** [comment]
I think that makes sense. There's one other issue, which is sort of a corner case, but happens when a user clicks the `Next` or `Back` button and then uses the browser's back button.

The `Next` and `Back` buttons use HTML5's history API behind the scenes, so clicking `Next` calls the [arethusaGoto](https://github.com/perseids-publications/treebank-template/compare/original-javascript..2019-11-06-javascript#diff-d934c504ff4f3f6db575f6f78c451e2eR3776) function and passes it the next sentence ID. Clicking the browser's back button will call the `arethusaGoto` function again but give it the previous sentence ID.

The problem happens when a user visits `/some-treebank?w=1`, clicks the `Next` button, and then clicks the browser's back button. In this case, the browser will show the URL `/some-treebank?w=1` but Arethusa won't actually highlight the word because the `arethusaGoto` function only takes the sentence ID as an argument.

I think the best way to deal with this is to have the `Next` and `Back` buttons be actual links instead of using the history API but only when there's a word highlighted. If we did it this way, the browser's back button would work correctly because it would reload the entire page instead of calling`arethusaGoto`. But it would still have the advantage of using the `arethusaGoto` most of the time, which speeds up browsing a treebank. Do you think this makes sense? It's a little bit of a clunky solution and I'm open to other suggestions.

**Comment by balmas** [comment]
> I think that makes sense. There's one other issue, which is sort of a corner case, but happens when a user clicks the `Next` or `Back` button and then uses the browser's back button.
> 
> The `Next` and `Back` buttons use HTML5's history API behind the scenes, so clicking `Next` calls the [arethusaGoto](https://github.com/perseids-publications/treebank-template/compare/original-javascript..2019-11-06-javascript#diff-d934c504ff4f3f6db575f6f78c451e2eR3776) function and passes it the next sentence ID. Clicking the browser's back button will call the `arethusaGoto` function again but give it the previous sentence ID.
> 
> The problem happens when a user visits `/some-treebank?w=1`, clicks the `Next` button, and then clicks the browser's back button. In this case, the browser will show the URL `/some-treebank?w=1` but Arethusa won't actually highlight the word because the `arethusaGoto` function only takes the sentence ID as an argument.
> 
> I think the best way to deal with this is to have the `Next` and `Back` buttons be actual links instead of using the history API but only when there's a word highlighted. If we did it this way, the browser's back button would work correctly because it would reload the entire page instead of calling`arethusaGoto`. But it would still have the advantage of using the `arethusaGoto` most of the time, which speeds up browsing a treebank. Do you think this makes sense? It's a little bit of a clunky solution and I'm open to other suggestions.

I think that really is an edge case, at least from the Alpheios perspective, so am not too concerned about it. I'm fine with the loss of the word highlighting when using the browser's back button. Thanks!
